options:
  db_host:
    type: string
    description: "PostgreSQL database host"
    default: ""
  db_name:
    type: string
    description: "PostgreSQL database name"
    default: "discourse"
  db_user:
    type: string
    description: "PostgreSQL database user"
    default: "wordpress"
  db_password:
    type: string
    description: "PostgreSQL database user's password"
    default: ""
  service_port:
    type: int
    description: "TCP port discourse should listen on"
    default: 80
  external_hostname:
    type: string
    description: "External hostname this discourse instance should respond to"
    default: ""
  enable_cors:
    type: boolean
    description: "Enable Cross-origin Resource Sharing (CORS) at the application level (required for SSO)"
    default: "true"
  cors_origin:
    type: string
    description: "Cors origin string to use, defaults to '*'"
    default: "*"
  developer_emails:
    type: string
    description: "Comma delimited list of email addresses that should have developer level access"
    default: ""
  smtp_domain:
    type: string
    description: "Hostname that email sent by this discourse should appear to come from"
    default: ""
  smtp_address:
    type: string
    description: "Hostname / IP that should be used to send SMTP mail"
    default: ""
  smtp_port:
    type: int
    description: "Port to use when connecting to SMTP server"
    default: 587
  smtp_authentication:
    type: string
    description: "Type of smtp authentication to use"
    default: "none"
  smtp_openssl_verify_mode:
    type: string
    description: "Should discourse verify SSL certs"
    default: "none"
  smtp_username:
    type: string
    description: "Username to use when sending mail via SMTP"
    default: ""
  smtp_password:
    type: string
    description: "Password to use when sending mail via SMTP"
    default: ""
  enable_local_sidekiq:
    type: boolean
    description: "Run sidekiq within the pod"
    default: "true"
  enable_local_redis:
    type: boolean
    description: "Run redis within the pod"
    default: "true"
  redis_host:
    type: string
    description: "Redis host name / IP"
    default: "127.0.0.1"
  serve_static_assets:
    type: boolean
    description: "Serve static assets with unicorn"
    default: "true"
