options:
  discourse_image:
    type: string
    description: "Discourse image to use"
    default: "discoursecharmers/discourse:v2.7.10-20.04_edge"
  image_user:
    type: string
    description: "Private registry username"
    default: ""
  image_pass:
    type: string
    description: "Private registry password"
    default: ""
  db_name:
    type: string
    description: "PostgreSQL database name. Defaults to Juju Application name."
    default: ""
  external_hostname:
    type: string
    description: "External hostname this discourse instance should respond to"
    default: "foo.internal"
  enable_cors:
    type: boolean
    description: "Enable Cross-origin Resource Sharing (CORS) at the application level (required for SSO)"
    default: "true"
  cors_origin:
    type: string
    description: "Cors origin string to use, defaults to '*'"
    default: "*"
  developer_emails:
    type: string
    description: "Comma delimited list of email addresses that should have developer level access"
    default: "user@foo.internal"
  smtp_domain:
    type: string
    description: "Hostname that email sent by this discourse should appear to come from"
    default: "foo.internal"
  smtp_address:
    type: string
    description: "Hostname / IP that should be used to send SMTP mail"
    default: "127.0.0.1"
  smtp_port:
    type: int
    description: "Port to use when connecting to SMTP server"
    default: 587
  smtp_authentication:
    type: string
    description: "Type of smtp authentication to use"
    default: "none"
  smtp_openssl_verify_mode:
    type: string
    description: "Should discourse verify SSL certs"
    default: "none"
  smtp_username:
    type: string
    description: "Username to use when sending mail via SMTP"
    default: ""
  smtp_password:
    type: string
    description: "Password to use when sending mail via SMTP"
    default: ""
  redis_host:
    type: string
    description: "Redis host name / IP"
    default: ""
  tls_secret_name:
    type: string
    description: "The name of the K8s secret to be associated with the ingress resource."
    default: ""
  throttle_level:
    type: string
    description: "Throttle level - blocks excessive usage by ip. Valid values: none, permissive, strict"
    default: none
  saml_sync_groups:
    type: string
    description: "Comma-separated list of groups to sync from SAML provider."
    default: ""
  saml_target_url:
    type: string
    description: "SAML authentication target url"
    default: ""
  force_saml_login:
    type: boolean
    description: "Force SAML login (full screen, no local database logins)"
    default: false
  max_body_size:
    type: int
    description: "Max allowed body-size (for file uploads) in megabytes, set to 0 to disable limits"
    default: 20
  s3_enabled:
    type: boolean
    description: |
      Store uploaded objects in an S3-compatible object storage service instead of a local directory.

      If true, sets DISCOURSE_USE_S3=true.
      Check https://meta.discourse.org/t/using-object-storage-for-uploads-s3-clones/148916 for more details.
    default: false
  s3_endpoint:
    type: string
    description: |
      The S3 endpoint to use.  This may be a non-Amazon S3-compatible endpoint.

      Sets DISCOURSE_S3_ENDPOINT
    default: "https://s3.amazonaws.com"
  s3_bucket:
    type: string
    description: |
      The S3 bucket to use.

      Sets DISCOURSE_S3_BUCKET.
      Required if s3_enabled is true.
    default: ""
  s3_access_key_id:
    type: string
    description: |
      The S3 access key ID to use.

      Sets DISCOURSE_S3_ACCESS_KEY_ID.
      Required if s3_enabled is true.
    default: ""
  s3_secret_access_key:
    type: string
    description: |
      The S3 secret key to use.

      Sets DISCOURSE_S3_SECRET_ACCESS_KEY.
      Required if s3_enabled is true.
    default: ""
  s3_region:
    type: string
    description: |
      The S3 region to use.

      Sets DISCOURSE_S3_REGION.
      Required if s3_enabled is true.
    default: ""
  s3_backup_bucket:
    type: string
    description: |
      The S3 bucket to use for backups.

      Sets DISCOURSE_S3_BACKUP_BUCKET.
      Also sets DISCOURSE_BACKUP_LOCATION=s3.
    default: ""
  s3_cdn_url:
    type: string
    description: |
      The S3 Content Delivery Network URL.

      Sets DISCOURSE_S3_CDN_URL.
    default: ""
