options:
  discourse_image:
    type: string
    description: "Discourse image to use"
    default: "discoursecharmers/discourse:v2.6.1"
  image_user:
    type: string
    description: "Private registry username"
    default: ""
  image_pass:
    type: string
    description: "Private registry password"
    default: ""
  db_name:
    type: string
    description: "PostgreSQL database name. Defaults to Juju Application name."
    default: ""
  external_hostname:
    type: string
    description: "External hostname this discourse instance should respond to"
    default: ""
  enable_cors:
    type: boolean
    description: "Enable Cross-origin Resource Sharing (CORS) at the application level (required for SSO)"
    default: "true"
  cors_origin:
    type: string
    description: "Cors origin string to use, defaults to '*'"
    default: "*"
  developer_emails:
    type: string
    description: "Comma delimited list of email addresses that should have developer level access"
    default: ""
  smtp_domain:
    type: string
    description: "Hostname that email sent by this discourse should appear to come from"
    default: ""
  smtp_address:
    type: string
    description: "Hostname / IP that should be used to send SMTP mail"
    default: ""
  smtp_port:
    type: int
    description: "Port to use when connecting to SMTP server"
    default: 587
  smtp_authentication:
    type: string
    description: "Type of smtp authentication to use"
    default: "none"
  smtp_openssl_verify_mode:
    type: string
    description: "Should discourse verify SSL certs"
    default: "none"
  smtp_username:
    type: string
    description: "Username to use when sending mail via SMTP"
    default: ""
  smtp_password:
    type: string
    description: "Password to use when sending mail via SMTP"
    default: ""
  redis_host:
    type: string
    description: "Redis host name / IP"
    default: ""
  tls_secret_name:
    type: string
    description: "The name of the K8s secret to be associated with the ingress resource."
    default: ""
  throttle_level:
    type: string
    description: "Throttle level - blocks excessive usage by ip. Valid values: none, permissive, strict"
    default: none
  saml_target_url:
    type: string
    description: "SAML authentication target url"
    default: ""
  force_saml_login:
    type: boolean
    description: "Force saml login (full screen, no local database logins)"
    default: false 
